val sehir = "İstanbul"
val ulke = "Türkiye"
var telefon = "+90 555 123 4567"
val postaKodu = "34000"
var email = "sevcanky.0240@gmail.com"
val meslek = "Yazılım Geliştirici"
var stokMiktari = 150
val musteriAdi = "Ahmet Yılmaz"
var bakiye = 2500.75
val dogumGunu = "1995-06-15"
var maas = 15000
val medeniDurum = "Bekar"
var urunYorum = "Ürün çok güzel, tavsiye ederim."
val odemeTarihi = "2025-04-27"
var odeme = 399.99
var siparisAdeti = 2
val arabaModeli = "Tesla Model 3"
val kitapAdi = "Suç ve Ceza"
val yayinlamaTarihi = "1866"
var indirimMiktari = 15
var odaSayisi = 3
val enlem = 41.0082
val boylam = 28.9784
val urunAdi = "Kablosuz Kulaklık"
var yemekFiyati = 120.50
val marka = "Apple"
val muzikAdi = "Bohemian Rhapsody"
var videoSuresi = "2 saat 15 dakika"
var urunPuani = 4.8
val resimAdi = "manzara.jpg"
val dosyaFormati = "jpg"
val renk = "Mavi"
val renkKodu = "#0000FF"
val telefonModeli = "iPhone 15"
val ekranBoyutu = 6.1
var agirlik = 180
val ulusalGun = "23 Nisan"
val tatilGunu = "1 Mayıs"
val rezervasyonTarihi = "2025-06-10"
val sokakAdi = "Cumhuriyet Caddesi"
var otobusHatti = "34M"
var kalanDakika = 8
val takipKodu = "TR123456789"
var kuponSuresi = "30 gün"
val kuponKodu = "INDIRIM30"
val faturaAdresi = "Atatürk Mah. No:10 İstanbul"